-- OnWork 그룹웨어 — PostgreSQL 스키마 (OnWork_데이터사전.pdf 기반, 21 테이블)
-- 데이터사전은 MySQL 표기(BIGINT AUTO_INCREMENT)였으나, 확정 아키텍처는 PostgreSQL이므로
-- IDENTITY 컬럼 + JSONB로 변환한다. 결재 전 실데이터 미반영 / soft delete 원칙 반영.
--
-- 스펙 갭(questions.md Q-001~002 참고):
--  - users.role(RBAC 5단계), users.position(직급)은 데이터사전엔 없으나 API/조직도가 요구 → 추가.
--  - approvals.ref_id, notifications.ref_id 등은 의도적 FK 미설정(다형 참조, 서비스 레이어에서 보장).

SET client_encoding = 'UTF8';

-- ============================================================ 공통 (Common)
CREATE TABLE work_groups (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name      VARCHAR(50)  NOT NULL,                 -- 예: 기본 9-to-6
    work_start_time TIME         NOT NULL,
    work_end_time   TIME         NOT NULL,
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE     -- TRUE 시 삭제 불가
);

CREATE TABLE departments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,                                    -- 상위 부서(자기참조). 최상위는 NULL
    name        VARCHAR(50)  NOT NULL,
    manager_id  BIGINT,                                    -- 팀장(users) — FK는 users 생성 후 ALTER로 추가
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_dept_parent FOREIGN KEY (parent_id) REFERENCES departments(id)
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT,                                  -- 미분류 시 NULL
    work_group_id BIGINT       NOT NULL DEFAULT 1,         -- 기본 9-to-6
    employee_no   VARCHAR(20)  NOT NULL UNIQUE,            -- 사번(자동 채번)
    name          VARCHAR(50)  NOT NULL,
    email         VARCHAR(100) NOT NULL UNIQUE,            -- 로그인 이메일
    role          VARCHAR(20)  NOT NULL DEFAULT 'EMPLOYEE' -- [추가] RBAC 5단계
                  CHECK (role IN ('CEO','VP','HR_MANAGER','MANAGER','EMPLOYEE')),
    position      VARCHAR(20),                             -- [추가] 직급(과장/대리/주임/사원 등)
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                  CHECK (status IN ('ACTIVE','INACTIVE','RESIGNED')),
    hire_date     DATE         NOT NULL,
    resign_date   DATE,
    resign_reason VARCHAR(200),                            -- 퇴사 처리 시 필수(앱에서 강제)
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_users_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_users_wg   FOREIGN KEY (work_group_id) REFERENCES work_groups(id)
);
-- RESIGNED 필터 성능(ADR-HR-003) 및 부서/근태 조회 인덱스
CREATE INDEX idx_users_status_resign ON users(status, resign_date);
CREATE INDEX idx_users_department ON users(department_id);

-- departments.manager_id → users (순환 FK는 users 생성 후 추가)
ALTER TABLE departments
    ADD CONSTRAINT fk_dept_manager FOREIGN KEY (manager_id) REFERENCES users(id);

CREATE TABLE user_credentials (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL UNIQUE,            -- users 1:1
    password_hash VARCHAR(255) NOT NULL,                   -- bcrypt
    updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_cred_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,                      -- 수신자
    type       VARCHAR(30)  NOT NULL,                      -- LEAVE_REQUESTED / ATTENDANCE_ANOMALY / HR_CHANGE_* 등
    ref_type   VARCHAR(20),                                -- LEAVE / ATTENDANCE / HR (FK 미설정)
    ref_id     BIGINT,
    message    VARCHAR(500) NOT NULL,
    is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW(),         -- 90일 보관 후 삭제 정책
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_notif_user_read ON notifications(user_id, is_read);

CREATE TABLE approvals (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          VARCHAR(20)  NOT NULL CHECK (type IN ('LEAVE','ATTENDANCE','HR')),
    ref_id        BIGINT       NOT NULL,                   -- 연결 모듈 PK (FK 미설정 — 서비스 레이어 보장)
    requester_id  BIGINT       NOT NULL,
    approver_id   BIGINT,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING','COMPLETED','CANCELLED')),
    action        VARCHAR(20)  CHECK (action IN ('APPROVE','ON_HOLD','REJECT')),
    reason        VARCHAR(500),                            -- ON_HOLD·REJECT 시 필수(앱)
    department_id BIGINT       NOT NULL,                   -- 팀장 조회 범위 필터
    processed_at  TIMESTAMP,
    CONSTRAINT fk_appr_requester FOREIGN KEY (requester_id) REFERENCES users(id),
    CONSTRAINT fk_appr_approver  FOREIGN KEY (approver_id)  REFERENCES users(id),
    CONSTRAINT fk_appr_dept      FOREIGN KEY (department_id) REFERENCES departments(id)
);
CREATE INDEX idx_appr_status_dept ON approvals(status, department_id);
CREATE UNIQUE INDEX uq_appr_type_ref ON approvals(type, ref_id);

-- ============================================================ 인사 (HR)
CREATE TABLE hr_change_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_type   VARCHAR(20)  NOT NULL CHECK (change_type IN ('CREATE','UPDATE','RESIGN')),
    target_user_id BIGINT,                                 -- CREATE 시 NULL
    payload       JSONB        NOT NULL,                   -- 변경 내용
    reason        VARCHAR(500),
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('DRAFT','PENDING','APPROVED','REJECTED','CANCELLED')),
    requested_by  BIGINT       NOT NULL,                   -- 경영지원팀
    approver_id   BIGINT,
    reject_reason VARCHAR(500),                            -- REJECTED 시 필수(앱)
    processed_at  TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    batch_id      VARCHAR(36),                             -- 일괄 승인 그룹(UUID)
    CONSTRAINT fk_hrc_target    FOREIGN KEY (target_user_id) REFERENCES users(id),
    CONSTRAINT fk_hrc_requester FOREIGN KEY (requested_by)   REFERENCES users(id),
    CONSTRAINT fk_hrc_approver  FOREIGN KEY (approver_id)    REFERENCES users(id)
);
CREATE INDEX idx_hrc_status ON hr_change_requests(status);

CREATE TABLE employee_change_histories (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id    BIGINT      NOT NULL,                -- 승인 완료 후이므로 NOT NULL
    change_type       VARCHAR(20) NOT NULL CHECK (change_type IN ('CREATE','UPDATE','RESIGN')),
    before_value      JSONB,                               -- CREATE는 NULL
    after_value       JSONB       NOT NULL,
    change_request_id BIGINT,                              -- 시스템 자동 변경 시 NULL
    changed_by        BIGINT      NOT NULL,                -- 승인자(경영진)
    changed_at        TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ech_target  FOREIGN KEY (target_user_id)    REFERENCES users(id),
    CONSTRAINT fk_ech_request FOREIGN KEY (change_request_id) REFERENCES hr_change_requests(id),
    CONSTRAINT fk_ech_changer FOREIGN KEY (changed_by)        REFERENCES users(id)
);

-- ============================================================ 근태 (Attendance)
CREATE TABLE daily_work_records (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL,
    date             DATE        NOT NULL,
    clock_in_at      TIMESTAMP,                            -- 서버 시각 기준
    clock_out_at     TIMESTAMP,
    overtime_minutes INT         NOT NULL DEFAULT 0,       -- 미승인 시간외 포함
    status           VARCHAR(20) NOT NULL DEFAULT 'NORMAL'
                     CHECK (status IN ('NORMAL','ANOMALY')),
    CONSTRAINT fk_dwr_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_dwr_user_date UNIQUE (user_id, date)     -- 당일 1회(중복 방지)
);
CREATE INDEX idx_dwr_date_status ON daily_work_records(date, status);

CREATE TABLE work_anomalies (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_work_record_id BIGINT      NOT NULL,
    anomaly_type         VARCHAR(30) NOT NULL
                         CHECK (anomaly_type IN ('LATE','EARLY_LEAVE','ABSENT','CLOCK_MISSING','UNAPPROVED_OVERTIME')),
    confirmed_by         BIGINT,                           -- 팀장. NULL = 미처리
    confirmed_at         TIMESTAMP,
    CONSTRAINT fk_wa_record  FOREIGN KEY (daily_work_record_id) REFERENCES daily_work_records(id),
    CONSTRAINT fk_wa_confirm FOREIGN KEY (confirmed_by)         REFERENCES users(id)
);

CREATE TABLE overtime_requests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL,
    request_date     DATE        NOT NULL,
    expected_start_at TIMESTAMP  NOT NULL,
    expected_end_at  TIMESTAMP   NOT NULL,
    reason           TEXT        NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                     CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    approver_id      BIGINT,
    reject_reason    VARCHAR(500),
    created_at       TIMESTAMP   NOT NULL DEFAULT NOW(),     -- 에이징/긴급도 산정용
    CONSTRAINT fk_ot_user     FOREIGN KEY (user_id)     REFERENCES users(id),
    CONSTRAINT fk_ot_approver FOREIGN KEY (approver_id) REFERENCES users(id)
);

CREATE TABLE monthly_summaries (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL,
    year_month        VARCHAR(7)  NOT NULL,                -- 예: 2026-04
    late_count        INT         NOT NULL DEFAULT 0,
    early_leave_count INT         NOT NULL DEFAULT 0,
    absent_count      INT         NOT NULL DEFAULT 0,
    total_overtime_minutes INT    NOT NULL DEFAULT 0,
    closed_by         BIGINT      NOT NULL,                -- 팀장
    closed_at         TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ms_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_ms_closer FOREIGN KEY (closed_by) REFERENCES users(id),
    CONSTRAINT uq_ms_user_month UNIQUE (user_id, year_month)
);

CREATE TABLE attendance_settings (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 싱글톤 id=1
    grace_in_minutes        INT     NOT NULL DEFAULT 10,
    grace_out_minutes       INT     NOT NULL DEFAULT 10,
    late_threshold_count    INT     NOT NULL DEFAULT 3,
    is_overtime_auto_collect BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by              BIGINT  NOT NULL,
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_as_updater FOREIGN KEY (updated_by) REFERENCES users(id)
);

-- ============================================================ 휴가 (Leave)
CREATE TABLE leave_types (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20)  NOT NULL UNIQUE,               -- ANNUAL / COMP / HALF_AM / HALF_PM
    name       VARCHAR(50)  NOT NULL,
    days_unit  DECIMAL(3,1) NOT NULL,                      -- 1.0 / 0.5
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE leave_settings (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 싱글톤 id=1
    annual_rollover         BOOLEAN NOT NULL DEFAULT FALSE,
    comp_expire_warning_days INT    NOT NULL DEFAULT 7,
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE leave_approvers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT    NOT NULL,
    approver_id   BIGINT    NOT NULL,                      -- 팀장
    delegate_id   BIGINT,                                  -- 대행자(ADR-003)
    is_absent     BOOLEAN   NOT NULL DEFAULT FALSE,        -- TRUE 시 delegate_id로 자동 전환
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_la_dept     FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_la_approver FOREIGN KEY (approver_id)   REFERENCES users(id),
    CONSTRAINT fk_la_delegate FOREIGN KEY (delegate_id)   REFERENCES users(id)
);

CREATE TABLE leave_balances (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    leave_type_id BIGINT       NOT NULL,
    total_days    DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    used_days     DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    expire_date   DATE,                                    -- 보상휴가만 사용
    year          SMALLINT     NOT NULL,                   -- 귀속 연도
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_lb_user FOREIGN KEY (user_id)       REFERENCES users(id),
    CONSTRAINT fk_lb_type FOREIGN KEY (leave_type_id) REFERENCES leave_types(id),
    CONSTRAINT uq_lb_user_type_year UNIQUE (user_id, leave_type_id, year)
);

CREATE TABLE leave_grants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_balance_id BIGINT      NOT NULL,
    granted_by      BIGINT       NOT NULL,                 -- 경영진만 부여(앱)
    grant_reason    VARCHAR(500) NOT NULL,
    expire_date     DATE         NOT NULL,
    granted_days    DECIMAL(4,1) NOT NULL,
    reason_type     VARCHAR(20)  NOT NULL DEFAULT 'ETC' CHECK (reason_type IN ('OVERTIME','ETC')),
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_lg_balance FOREIGN KEY (leave_balance_id) REFERENCES leave_balances(id),
    CONSTRAINT fk_lg_granter FOREIGN KEY (granted_by)       REFERENCES users(id)
);

CREATE TABLE leave_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    leave_balance_id BIGINT      NOT NULL,
    start_date      DATE         NOT NULL,
    end_date        DATE         NOT NULL,
    days_used       DECIMAL(4,1) NOT NULL,
    reason          VARCHAR(500),
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                    CHECK (status IN ('PENDING','APPROVED','ON_HOLD','CANCELLED')),
    approver_id     BIGINT,
    is_delegated    BOOLEAN      NOT NULL DEFAULT FALSE,   -- 대행자 처리 시 TRUE
    hold_reason     VARCHAR(500),                          -- ON_HOLD 시 필수(앱)
    approved_at     TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_lr_user     FOREIGN KEY (user_id)          REFERENCES users(id),
    CONSTRAINT fk_lr_balance  FOREIGN KEY (leave_balance_id) REFERENCES leave_balances(id),
    CONSTRAINT fk_lr_approver FOREIGN KEY (approver_id)      REFERENCES users(id)
);
CREATE INDEX idx_lr_user_status ON leave_requests(user_id, status);

CREATE TABLE leave_histories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_balance_id BIGINT      NOT NULL,
    leave_request_id BIGINT,                               -- 수동 부여 시 NULL
    change_type     VARCHAR(20)  NOT NULL CHECK (change_type IN ('GRANT','USE','CANCEL','EXPIRE')),
    change_days     DECIMAL(4,1) NOT NULL,                 -- 차감 시 음수, 부여/취소 시 양수
    before_days     DECIMAL(4,1) NOT NULL,
    after_days      DECIMAL(4,1) NOT NULL,
    changed_by      BIGINT       NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_lh_balance FOREIGN KEY (leave_balance_id) REFERENCES leave_balances(id),
    CONSTRAINT fk_lh_request FOREIGN KEY (leave_request_id) REFERENCES leave_requests(id),
    CONSTRAINT fk_lh_changer FOREIGN KEY (changed_by)       REFERENCES users(id)
);

-- ============================================================ 온보딩 (Onboarding)
CREATE TABLE onboarding_tutorial_progress (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    tutorial_code VARCHAR(30) NOT NULL,                    -- NEW_HIRE_TOUR / MANAGER_TOUR
    status        VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED'
                  CHECK (status IN ('NOT_STARTED','IN_PROGRESS','COMPLETED','DISMISSED')),
    current_step  SMALLINT    NOT NULL DEFAULT 0,
    last_shown_at TIMESTAMP,
    dismissed_at  TIMESTAMP,
    completed_at  TIMESTAMP,
    created_at    TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_otp_user_tutorial UNIQUE (user_id, tutorial_code)
);

-- ============================================================ 일정 (Schedule) — 오늘의 일정
CREATE TABLE schedules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    date        DATE         NOT NULL,
    start_time  TIME,
    end_time    TIME,
    title       VARCHAR(200) NOT NULL,
    kind        VARCHAR(20)  NOT NULL DEFAULT 'MEETING'    -- MEETING / TASK / PERSONAL
                CHECK (kind IN ('MEETING','TASK','PERSONAL')),
    CONSTRAINT fk_sch_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_sch_user_date ON schedules(user_id, date);

-- ============================================================ 급여 (Salary) — 마이페이지 전용
CREATE TABLE salaries (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT  NOT NULL UNIQUE,
    base_pay            INT     NOT NULL,                  -- 기본급(월, 원)
    meal_allowance      INT     NOT NULL DEFAULT 0,        -- 식대
    transport_allowance INT     NOT NULL DEFAULT 0,        -- 교통비
    position_allowance  INT     NOT NULL DEFAULT 0,        -- 직책수당
    pay_day             INT     NOT NULL DEFAULT 25,       -- 급여 지급일
    CONSTRAINT fk_sal_user FOREIGN KEY (user_id) REFERENCES users(id)
);
